### ISSUE TITLE
Problems importing SLP files - predictions can be imported, project files cannot

### ISSUE THREAD

**Issue by rfkova** [sgoldenlab/simba#184]
I have an SLP file which has predictions in it. I would like to use the current predictions therein in SimBA but I get an error when I try to import it. 

If I run inference on the entire file to generate a new set of predictions the predictions file is usable. Due to a bug I'm experiencing in SLEAP this process generates much worse predictions than the original file so I would just like to use those. 

I am assured by the SLEAP team that there should be no difference in SLP file format between predictions and the project files. Both should contain predictions that could be used. 

@sronilsson was looped into [this github discussion ](https://github.com/talmolab/sleap/discussions/760) that has more details and I've set up drive access to the requested files. Please see .txt therein to explain each file (I included the video itself as well).

If any further details are necessary I will edit the Issue :)

**Comment by sronilsson** [comment]
Hi @rfkova! 

SimBA first reads in the number of frames with predictions in your `labels.v000.video0.slp` SLP file. For this it counts the number of entries in the `['frames’]` key in the SLP file, and finds an array of `55391` entries. 

Next, it to get the actual body-part predictions, SimBA looks in the ['predicted_points’] key in the SLP file and finds 329244 rows. If we divide 329244 by the number of body-parts (which is 6), we get predictions for `54874` frames.

PS: When looking at the number of frames in the actual video, there seems to be a count of `107914`.

The `(cannot set a row with mismatched columns)` you are seeing happens when SimBA tries to analyze frame `54875` of the anticipated `55391` frames. This returns zero body-part predictions. SimBA tries to insert the zero body-part predictions into 6*3 (body-part count * (X, Y, P)) column dataframe, just like the the other prior predicted frames. But - with zero values - that’s not going to work and it fails. 

I have not seen this error before, there is a few things we can do. We can insert a fix where we treat the ['predicted_points’] key as the actual true frame count, or alternative the true frame count is whatever is the smallest (['predicted_points’] or ['frames’]). However the two counts normally match up, I don’t know why it wouldn’t match up here, and even if we use one of these solutions, we’d still only have predictions for the first half-ish of the video. Let me know if that makes sense!

**Comment by sronilsson** [comment]
Hi @rfkova - sorry forgot to provide an update on this. If you upgrade simba `pip install simba-uw-tf-dev --upgrade` you should be able to import your slp data, but please let me know if you get into any issues! That said, I am not sure the tracking performance will be good enough

**Comment by rfkova** [comment]
Hi @sronilsson!

Amazing, just tried it out and the import works perfectly!!! Astoundingly I'm still troubleshooting the rest of my workflow so this is super nice to be able to get a feel for SimBA in the meantime.

Thank you so much for your help!!!
