### ISSUE TITLE
SIMBA COMPLETE: ROI definitions saved for video: {self.file_name}  🚀

### ISSUE THREAD

**Issue by Gfernandezv** [sgoldenlab/simba#275]
**Describe the bug**
every time that I try to save my ROI, the follow message appears:
SIMBA COMPLETE: ROI definitions saved for video: {self.file_name}  🚀

as consequence of that, I cannot make any analysis of my data.

**Comment by sronilsson** [comment]
Hi @Gfernandezv! 

If I understand correctly, you press this button to save your ROI data amd you see the `SIMBA COMPLETE: ROI definitions saved for video: {self.file_name}` msg.

<img width="479" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/56f8b191-9775-47c7-9cfd-1eff23dd64cd">

Next, when you go on to analyse your data ROI data, through e.g., `ANALYZE ROI DATA: AGGREGATES` like the menu below, do you hit an error msg? 

<img width="993" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/f201e66d-1e0f-4072-8f2a-93668ed1d5a6">

PS: The text preinted `SIMBA COMPLETE: ROI definitions saved for video: {self.file_name}` contains a typo, you should see your actual video name rather than `{self.file_name}`, but that should be fixed if you update simba with `pip install simba-uw-tf-dev --upgrade`, and it should not affect the analysis functions.

**Comment by Gfernandezv** [comment]
Hi, thanks for the quick answer. 
I upgrade simba and it solved the problem, but when I try to analyse de data using ANALYZE ROI DATA: AGGREGATES.

![image](https://github.com/sgoldenlab/simba/assets/87041514/ca4e45e6-8354-4596-a0c1-db6e8ec79c61)
 
I have the follow message in the console:
![image](https://github.com/sgoldenlab/simba/assets/87041514/52987824-2d7e-44dc-af6d-56e17332daec)

and no message is print in the main screen:
![image](https://github.com/sgoldenlab/simba/assets/87041514/689c5207-63ef-4a81-bb55-e1b4d515eeec)

(I´m using: Anaconda, with python 3,6 on windows 10)

**Comment by sronilsson** [comment]
Ah thanks @Gfernandezv! 

I think this error comes from the center of ROIs being saved with names `centerX` and `centerY` in **older** version of SimBA, and `Center_x` and `Center_y` in **newer** versions of SimBA (although I thought I had inserted a fix for this - I will have to check tomorrow why this fix isn't working). 

In meantime, if not too much hassle, you can try to redraw the ROIs in newest version and see if that fixes it.

**Comment by sronilsson** [comment]
@Gfernandezv - I had a look, and can't identify how the error is happening: not sure which older version you where using. 

To solve it, would you mind zipping up the `/project_folder/logs/measures/ROI_definitions.h5` file and dropping it into this issue in I will take a look what the key names are and insert a fix?

**Comment by Gfernandezv** [comment]
Hi, I already solve the problem. To do it, I made a fresh install using the Anaconda tutorial (https://github.com/sgoldenlab/simba/blob/master/docs/anaconda_installation.md) and then update (using `pip install simba-uw-tf-dev)`

Just one thing, when a tried to add the DLC CSV files it gives an error. To solve it, i had to delete the input csv folder and add the csv files after of load the experiment file.

Thanks for your helpfull tips
=)

**Comment by sronilsson** [comment]
Thanks @Gfernandezv! if you come across the import error again, let me know what the error msg in the OS system terminal is. Seems to be some SimBA version clashes when projects/roi definitions from older versions are used in newer versions and want to get rid of them if possible.
