### ISSUE TITLE
Successful but then empty CSV upon analysing ROI data

### ISSUE THREAD

**Issue by neurorie** [sgoldenlab/simba#285]
**Describe the bug**
When analysing ROI data, product is empty csv files

**To Reproduce**
1. Go to 'ROI'
2. Click on 'Analyze ROI Data: Aggregates'
3. Initial error:
![Screenshot 2023-09-08 161956](https://github.com/sgoldenlab/simba/assets/144468935/54b741b4-6af7-4ee6-8fcf-94c75fed8acd)

4. Manually modified video names in the video_info files to match the shortened video names. 
5. No error given but empty csv files. Also, to check the ROI selection, I need to open csv before manually shortening it.

![Screenshot 2023-09-08 162154](https://github.com/sgoldenlab/simba/assets/144468935/97382d40-2636-443e-9690-9e1e1ab11610)

**Expected behavior**
Filled ROI analysis data in csv files, which will allow me to analyse data and also to visualise video. When I try to visualise the video, potentially due to the empty csv, this error is given.
![Screenshot 2023-09-08 162301](https://github.com/sgoldenlab/simba/assets/144468935/aed0b496-c1e7-4e59-8b63-a1eedeb7c2e9)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Python Version Python 3.10.10
 - Are you using anaconda? Yes

**Comment by sronilsson** [comment]
Hi @neurorie, thanks for reporting and the screengrabs, very helpful for troubleshooting.

Not sure entirely what is happening but appears to be a mixup between the CSV file names in your project, and the video files names in the project. SimBA uses the names of the videos to get them accurately paired with the respective data files. 

Let's say I decide to draw ROIs 10LfamDLC_resent_50_2023_JCRMSPRINT_2000labelled and click draw here first:

<img width="773" alt="image" src="https://github.com/sgoldenlab/simba/assets/34761092/ab34eee1-fde6-40fe-82f9-18dfa0c1a26e">

After drawing, SimBA then saves all your drawing information for this video under the name "10LfamDLC_resent_50_2023_JCRMSPRINT_2000labelled" inside the `project_folder/logs/measures/ROI_definitions.h5` of your project. 

Next, you go on to click on `Analyze ROI Data: Aggregates`. SimBA loops over each CSV file you have in the `project_folder/csv/outlier_corrected_movement_location`. Let's say the first file is `10Lfam.csv`. SimBA then looks inside the `ROI_definitions.h5`, for what kind of ROIs you have associated with `10Lfam`. In this case there will be no ROIs, because the ROIs you drew are for video named "10LfamDLC_resent_50_2023_JCRMSPRINT_2000labelled". If this is the case for all videos, you end up with an empty CSV. 

Let me know if this if this could be the reason!

**Comment by neurorie** [comment]
Hello, thank you for the response!

I have tried opening the H5 file with an online viewer and as I am concerned, there are no csv files. Or should I properly open with a viewer and check the content?
![Screenshot 2023-09-11 093057](https://github.com/sgoldenlab/simba/assets/144468935/0282eb5e-e656-4d9b-9f0c-dc70132d337e)

In the project_folder/csv/outlier_corrected_movement_location, I have shortened name listed there with all csv files. Before, when it was working, I remember the shortened name was shown when drawing ROI so I am not sure why there is this discrepancy.

**Comment by sronilsson** [comment]
Hi @neurorie,

To open the `ROI_definitions.h5` file, you can use[THIS](https://github.com/sgoldenlab/simba/blob/master/docs/Tutorial_tools.md#extract-roi-definitions-to-human-readable-format) tool under the heading *Extract ROI definitions to human-readable format*.

However, this will only allow you to view the information for the ROIs you have drawn (including the video names), not to edit. 

I suggest this:

(i) use the tool above to extract the ROI information, to confirm that you have drawn ROIs on videos names e.g.,  `10LfamDLC_resent_50_2023_JCRMSPRINT_2000labelled`.

(ii) If true, then, delete all your ROi definitions with [THIS](https://github.com/sgoldenlab/simba/blob/master/docs/ROI_tutorial_new.md#delete-all-roi-definitions-in-your-simba-project) button.

(iii) Rename your video names to be in agreement with file names: e,g., `10LfamDLC_resent_50_2023_JCRMSPRINT_2000labelled.mp4` is renamed to `10Lfam.mp4`. 

(iv) Redraw your ROIs and analyze your data. 

If this is not possible (you have drawn so many ROIs that it would take ages to draw them again), let me know and I will give you code that renames the video names in the `ROI_definitions.h5` file.

**Comment by neurorie** [comment]
![Screenshot 2023-09-11 164046](https://github.com/sgoldenlab/simba/assets/144468935/e5723484-ec3d-4453-bccd-521d023a4d08)
Hello again, I cannot seem to find the button under the tools. My SimBA version is 1.62.3

**Comment by sronilsson** [comment]
If you update simba by typing `pip install simba-uw-tf-dev --upgrade` in the windows terminal, do you see it?

**Comment by neurorie** [comment]
Yes, perfect! I will try it now.

**Comment by neurorie** [comment]
![image](https://github.com/sgoldenlab/simba/assets/144468935/ef0913f6-192e-46d1-8b00-d914ab6cbdc1)
I got an error mid-way but I can see some ROI info for rectangle and it seems that I do need to delete ROI and rename the video. For this, I can just change the names in the videos file, right?

**Comment by sronilsson** [comment]
Thanks for posting the error, very helpful, the error is just a printing error typo by me that I will fix now and does not affect the output. 

Yes, just change the video files names directly in the `project_folder/videos` directory.

**Comment by neurorie** [comment]
It worked perfectly, thank you so much :)
