### ISSUE TITLE
Automatically track frames annotated for each labeling session

### ISSUE THREAD

**Issue by Ejdrup** [sgoldenlab/simba#30]
Rather than having the user supply the exact frame range labeled in the session to avoid erasing all previous labeling when saving (ouch I lost a lot of hours), I suggest tracking the frames actively labeled for each session, and then overwriting only those.

**Comment by sgoldenlab** [comment]
Hej @Ejdrup - sorry about the lost hours!! There are two buttons under the label behavior tab. When using the first, SimBA assumes you are starting afresh, and a new file will be generated (if any previous annotations are there, they will be overwritten). The second assumes you are continuing a previously saved annotation session, and previous annotations are added to, rather than overwritten. 

![image](https://user-images.githubusercontent.com/50497030/80812714-54512b80-8b7d-11ea-91aa-9639262789af.png)

**Comment by Ejdrup** [comment]
I am already using that function. However, saving after loading a save session overwrites the old session with only the newly annotated frames, unless the specific range to save is specified. I suggest automatically embedding that function, so pressing save does not overwrite the entire file, if no range has been supplied under frame range.

**Comment by sgoldenlab** [comment]
Thanks - I'll look over this today.

**Comment by inoejj** [comment]
@Ejdrup The bug had been reintroduced by mistake and it is fixed now. Please download the latest version of SimBA and test it out. Please test out the labelling and load labelling for a minute and see if it works for you. 

Please let me know if you have anymore questions, I would be more than happy to assist you.

Sincerely,
JJ
