### ISSUE TITLE
SHAP Multiprocessing Failed

### ISSUE THREAD

**Issue by AndyWeasley2004** [sgoldenlab/simba#360]
My error looks like this and I have set multicore to be True.
![IMG_0945](https://github.com/sgoldenlab/simba/assets/110661816/02ae8780-a0bd-44c8-84d8-be9fa9244956)

My CPU info is below:
![IMG_0946](https://github.com/sgoldenlab/simba/assets/110661816/48072bcf-8968-421d-ac36-6582e8378e4d)
Is multiprocessing not supported on this CPU? Thank you for your information.

**Comment by sronilsson** [comment]
Yes it should be supported, it should run them in parallel on each of your selected cores, your computer looks good.

I haven't seen this error before. It looks like it is trying to process some large value which is larger than or smaller than 2148483648 which is more than a 32bit floating point can handle... possibly? I am away for the next couple of days but will see if I can recreate this and get back to you.

**Comment by sronilsson** [comment]
... @AndyWeasley2004 One thing you could help me with:

If you try it on fewer cores - e.g., 5 does it run? 

Or does it run of you build the model with fewer trees/estimators? Say 200? 

It could be a RAM related issue if those things fixes it.

**Comment by AndyWeasley2004** [comment]
I will try that when I go back to work. Thank you for your information!

**Comment by sronilsson** [comment]
👍🏻 I googled around and yes, the issue is discussed [here](https://stackoverflow.com/a/47776649) as a possible memory error. 

I don't know how much data you have, but if above doesn't fix it, check if it would run with less data (fewer, or smaller files inside the `project_folder/csv/targets_inserted` directory). If it runs then it would also suggest memory related.
