### ISSUE TITLE
Issue when loading .h5 files. Fuzzy instructions. 

### ISSUE THREAD

**Issue by DorianBattivelli** [sgoldenlab/simba#44]
Hello, 

I'm using SimBA for the first time, and I have an issue just after clicking "import h5". The instructions are fuzzy and I cannot read what is asked. Here a picture:

![Untitled](https://user-images.githubusercontent.com/66886884/87134203-a3f85580-c298-11ea-88db-c119d156bada.png)

I tried to recreate a new project several times, but I obtain systematically the same issue. would you have some suggestion to fix that bug?

FYI: I am using windows 10, and my training has been done on maDeeplabcut 2.2.b6 with 8bp. I worked on mov format for dlc analysis, and then I converted them in mp4 to switch on SimBA.

Thank you for the help, 
Best, 
Dorian

**Comment by sgoldenlab** [comment]
Hi @DorianBattivelli - many thanks for reporting this, it's very helpful and I appreciate it. It's my mistake / bug, I'm printing the text with too big line width, which depends on the resolution of your videos, so if you work on smaller resolution videos, then it can start to look fuzzy like this and difficult to read, and I will fix it. But, meanwhile, if you wanted to fix it yourself! (It's a small change):

1). Go to your this file in your where SimBA is installed, likely something similar to this: `C:\Python36\Lib\site-packages\simba\read_DLCmulti_h5_function.py`. Open the file and change these values to either 1 or 2 rather than the original 3 and it should look much better. 

![image](https://user-images.githubusercontent.com/50497030/87162194-73a1be80-c27a-11ea-9e99-e7d039320106.png)

2). Save your updated file and restart SimBA!

I will however fix it in the next update with some other fixes - hopefully I have it done by end of weekend.

**Comment by DorianBattivelli** [comment]
@sgoldenlab , it works now, thank you very much!

**Comment by sgoldenlab** [comment]
Great! 👍
