### ISSUE TITLE
error importing SLEAP .slp file

### ISSUE THREAD

**Issue by L-Jacinto** [sgoldenlab/simba#53]
When trying to import a .slp file into simba I get the following error in "project configuration / import tracking data":

![simba_error](https://user-images.githubusercontent.com/68620126/88539499-45a5d380-d009-11ea-97ed-caa7a80f190d.png)

I have imported the corresponding video in "project configuration / import videos into project folder".

What is the cause of this issue? Any suggestions on how to solve it?

**Comment by sgoldenlab** [comment]
Hi @L-Jacinto! First I don't have an intimidate idea for a fix and will need to know more. 

The cause is SimBA looking for the associated video file name which is stored inside of the SLP file (it is typically stored in a dictionary called `provenance` within an entry called `video.path`), and SimBA can't find this entry, and it breaks. 

The reason could be that SLEAP has changed their SLP structure slightly (for naming and structure), or the `video.path` entry is only generated when SLP files are created through some architectures, not others, for example. 

It's difficult for me to troubleshoot from scratch, as I'd have to try and recreate your tracking model. Would you mind sharing your SLP file you are trying to import to a gdrive link? It would be much quicker for me to find out the cause that way. Thanks!

**Comment by L-Jacinto** [comment]
Hi. Thank you for the quick reply.

I'd be happy to share the .slp and video files if that helps solving the issue. Is there an email address I can send the link to?

Thanks again.

**Comment by L-Jacinto** [comment]
Additionally, I see in the error, that it's looking for a SLEAPbottom-up file; but the tracking file we've generated in SLEAP was from a top-down model. Can that be the issue? Does SIMBA support tracking generated by both approaches (bottom-up and top-down)?

**Comment by sgoldenlab** [comment]
I was thinking that could also be the case, as I only worked with bottom up when I created the pipeline in SimBA and assumed the output file structure would be the same though both methods. If you share your file, I could make sure it work both ways. 

Could you share it with snilsson@uw.edu?

**Comment by L-Jacinto** [comment]
Sent. Thank you.

**Comment by sgoldenlab** [comment]
Cheers, got it thanks! I took a peak and the meta-data in the SLP does not contain a video name, it's an empty list - I am not sure why this would be - it could be a bottom up vs top down thing. Thus, it will be difficult for SimBA right now to know what video-file the the SLP belongs to, especially when the videos and associated file names are different like this:

![image](https://user-images.githubusercontent.com/50497030/88569349-2dc15600-cfef-11ea-9226-7798860e1051.png)

I am inserting a fix now for you to try. If SimBA finds an empty video name like this, it will re-name the imported CSV as the same filename as the original slp file. The following msg will also be printed:

'Warning: The video name could not be found in the .SLP meta-data table. SimBA therefore gives the imported CSV the same name as the SLP file. To be sure that SimBAs SLEAP import function works, make sure the imported SLP file(s) and the associated video file(s) has the same file name - e.g., "Video1.slp" and "Video1.slp" etc, before importing the videos and SLP files to SimBA.')

I let you know when the fix is up, let me know if that makes sense.

**Comment by sgoldenlab** [comment]
It's up - can you give it a go after upgrading SimBA to version 1.2.9?

**Comment by L-Jacinto** [comment]
Great. Thanks for the update, it seems its solves the import .slp file issue. However, we now have a different error (the same reported on issue #54)

![simba_error_2](https://user-images.githubusercontent.com/68620126/88577932-aa7c2080-d03f-11ea-8ca9-c5713c05dbda.png)

For the bodyparts we use the simba model for 2 animals / 8 bdp.

**Comment by sgoldenlab** [comment]
I'm onto it! Thanks for reporting this @L-Jacinto

**Comment by sgoldenlab** [comment]
@L-Jacinto - can you try again (SimBA version 1.2.10) and let me know how it goes. 

Basically, what was happening for some reason - is that your tracks where called "track 14" and "track 15", while SimBA expected the first two tracks to be called "track 0" and "track 1". SimBA filled in all the data for "track 14" and "track 15", and then generated two further empty tracks (track 0-1) because it assumed those animals where in your dataset and they were occluded. 

So you ended up with 4 tracks, but only a dataframe big enough for 2 tracks, so it failed and threw you that error msg. 

PS. I visualized an image or two of your tracking, it was not amazing but I don't think it is a SimBA error right now - it may be worth going back to SLEAP later on and improving it. 

Let me know how it goes!

**Comment by L-Jacinto** [comment]
Amazing - it worked. Thank you so much for your help.

However, the bodypart labels seems off in the frame to identify the animals when compared with the original video (we browsed several frames, and in most of them the labels seemed off) (even though, you are right, the tracking is not so good on that video; it was just a quick inference video from a poorly trained network to test the full SLEAP-to-SIMBA pipeline).

To ensure it was not a video problem, we tested with another video with better tracking, and we got a new error this time:

![error3](https://user-images.githubusercontent.com/68620126/88588044-d0f58800-d04e-11ea-841d-ad4a1c3d7513.png)

In case you want to check it I'm sending you the video and .slp file via email.

ps. Indeed, SLEAP can call tracks any number/name, it does not necessarily label two animals with track0 and track1 (especially if you have multiple tracks from the inference step).

**Comment by L-Jacinto** [comment]
Apparentely there was something wrong with that .slp file. We generated a new one and it worked. 

However, the labels are still off when compared with the SLEAP-labeled video; and perhaps that may be the reason why the tracking was apparentely not so great in the frames you saw. 

I will mail you the original video, sleap-labeled video and .slp file, so you can have a look.

thank you again for your great help.

**Comment by sgoldenlab** [comment]
Thanks - I will take a look a little later today! Sounds like there may be an alignment issue with the tracking and the frames when the tracks are labelled differently than beginning with zero.

**Comment by L-Jacinto** [comment]
Also, since the updates we have been enable to properly open the "load project menu" (either with DLC or SLEAP-based projects):

![empty_menu](https://user-images.githubusercontent.com/68620126/88603477-f09ba900-d06c-11ea-9309-c13088b5722a.png)

We get the following error on the console:

![error4](https://user-images.githubusercontent.com/68620126/88603488-f98c7a80-d06c-11ea-98b2-ccf4de50a86a.png)


This was working fine for us before (at least with DLC files).

**Comment by sgoldenlab** [comment]
Ah sorry I had this conversation with someone the other day, it is a problem with the names of the body-parts. I'm going to paste it here to see if it helps you: 

sgoldenlab @sgoldenlab Jul 23 21:57
I'm however suprised that you weren't able to boot up your project. Could you send me a screengrab of the content of your project_folder\logs\measures\pose_configs\bp_names\project_bp_names.csv file to help me understand it?

CarmenWinters @CarmenWinters Jul 23 21:59
![image](https://user-images.githubusercontent.com/50497030/88604961-77309600-d02d-11ea-82e9-b62f683277e6.png)

sgoldenlab @sgoldenlab Jul 23 22:04
Thank you, is this the order they appear in the CSV tracking file?
Like, the order you labelled them in DLC?

CarmenWinters @CarmenWinters Jul 23 22:04
Yep!

sgoldenlab @sgoldenlab Jul 23 22:17
Ah thanks, SimBA needs a way of telling which animal is which, and currently it does so by looking for numbers in the animal bodypart names. If you try to rename the animals "Mother_1", "Pup_2", and "Mother_3", I think it might work. It should help you start the project.
I'll fix the code to look for the names of the animals instead

CarmenWinters @CarmenWinters Jul 23 22:27
IT WORKED!!!! Thank you! You are a magician!

**Comment by sgoldenlab** [comment]
Is it right that you can no longer open projects that you could previously open though?

**Comment by sgoldenlab** [comment]
Looking at the sleap import error now - thanks for the labeled video also, very helpful.

**Comment by sgoldenlab** [comment]
Hi @L-Jacinto - I've been trying to make sense of it but cannot get my head around it at the moment. Looking at your SLEAP, there is an initial track for animal 14 in frame 0. One of the body-parts in this track is located at x=419, y = 152. But this is not at all near where the animals are in frame 0, and do not match with the labeled video you sent. Just wanted to check: have you rotated, clipped or cropped the video in any way after performing the tracking? 

![image](https://user-images.githubusercontent.com/50497030/88615002-d4d0dc80-d045-11ea-91ba-1846902b4c1e.png)

**Comment by L-Jacinto** [comment]
Regarding the project loading: we are not naming any bodyparts, we are using the predefined simba "multi tracking / multianimals, 8 bps" model. And correct, we can no longer load projects created after the update. With the exact same project configuration and video files we were able to create and load before the update.

**Comment by L-Jacinto** [comment]
Here is the screengrab of the bodyparts file:

![bdps_scp](https://user-images.githubusercontent.com/68620126/88649250-9e37a800-d0bf-11ea-89b2-8484dbc868c8.png)

**Comment by L-Jacinto** [comment]
Regarding the tracking issue. That is really odd. We did not crop, rotate or change the video in any way after tracking. The video I sent you is the same video we used to train the network, infer the tracks and then export the .slp file we are trying to import into SIMBA.

**Comment by L-Jacinto** [comment]
Regarding the project loading: I reverted to version 1.2.7 and the projects load just fine (ie. all options on all tabs in "load project" show up, and operations - video parameters, label behavior, etc - are functional).

From version 1.2.9, the loading stops working (for the files/projects that previously worked).

**Comment by sgoldenlab** [comment]
Thanks again @L-Jacinto for reporting this. I will dig into it more - I should have another tracking data file from the same tracking set up from the user user experiencing similar issues as you and maybe this will help me make sense of it.

**Comment by L-Jacinto** [comment]
We reverted to version 2.1 and were able to go through the whole process with a .slp file without any errors. The labels now appear in the correct position as well. With versions 2.5 onward we get all kind of errors, including the ones reported here. (did not test between versions 2.1 and 2.5)

**Comment by L-Jacinto** [comment]
We have also narrowed down one of the issues:  the mispositioned labels. The .slp file that needs to be imported into SIMBA is NOT the "main" .slp generated in "file/save" in SLEAP; but the one found in the folder "\predictions". With this file, all labels appear in the correct position and the video.path error does not occur (regardless of the file names).

-

**Comment by sgoldenlab** [comment]
Thanks @L-Jacinto - that's great to know

**Comment by L-Jacinto** [comment]
Just an update, regarding the .slp to be imported and the mispositioned labels. Using the s.lp file found on the "\predictions" folder in SLEAP works well to solve the mispositioned labels and video.path errors but has a major caveat: corrections to the inference (which are much needed to refine the tracking/labeling and avoid the extract features errors in SIMBA) will not be saved into the predictions .slp. 

SIMBA should definitely look into this, trying to find a way for users to import the main .slp (which allows saving changes/updates to labels/tracking) without the mislabeling error.

**Comment by sgoldenlab** [comment]
Hi @L-Jacinto - that does sound like a major caveat. So if I understand correctly - after running inference on the video, SLEAP saves two separate h5 SLP files - one with additional track corrections and one without track corrections, and SimBA only works on the one without? The file we worked on earlier, was that the SLP file with corrections? I'm trying to get my head around the idea why SLEAP would save a SLP with erroneous tracks. 



Unfortunately I have other pressing things happening at the lab at the moment, so I won't be able to dig deep into this right now but will help as much I can.

**Comment by L-Jacinto** [comment]
Whenever you save on "File/Save" on SLEAP's menu a .slp file - that is created the first time you click save - is updated. I can only assume that this would be the .slp file that contains the most current labels and tracks. However, that was the file I had sent you previously and that created the mispositioned labels in SIMBA (and originated the video.path error before v2.9 update).

Additionally, whenever you run an inference on SLEAP, a prediction .slp is also generated in a "/predictions" folder. That file cannot be updated by subsequent changes to the inference result. However, when loading this file into SIMBA we get the labels in the correct position (and the video.path error does not occur, regardless of the file names). (but, as reported, has the caveat of not allowing prediction's refinement, which is crucial)

On top of that, it is also possible to export a .h5 file from "File/Export Analysis HDF5". But SIMBA cannot load this file.

**Comment by L-Jacinto** [comment]
so, no solution for this?

**Comment by smidm** [comment]
@LJ-lab thank you for reporting the bug. Please include the console output / stacktrace in plain text next time. I'm experiencing the same issue, but I was not able to find this issue due to the screenshots. See [how to copy from command prompt on Windows](https://www.laptopmag.com/articles/how-to-windows-10-command-prompt-copy).

I'm including the bug in text:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/matej/local/conda/envs/simba/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/matej/local/conda/envs/simba/lib/python3.6/site-packages/simba/SimBA.py", line 3055, in importh5
    importSLEAPbottomUP(self.configinifile,self.h5path.folder_path,idlist)
  File "/home/matej/local/conda/envs/simba/lib/python3.6/site-packages/simba/sleap_bottom_up_convert.py", line 52, in importSLEAPbottomUP
    videoName = os.path.basename(final_dictionary['provenance']['video.path']).replace('.mp4', '')
TypeError: 'NoneType' object is not subscriptable
```
