### ISSUE TITLE
ROI feature?

### ISSUE THREAD

**Issue by 2909ft** [sgoldenlab/simba#6]
Hello everybody!

First of all, thank you for developing SimBA :) I was wondering if in the future it would be possible to add a feature that would allow users to define a ROI and use that feature as part of the classifier training. 

Thanks!
Filipa

**Comment by sgoldenlab** [comment]
:) that and more in regard to ROIs coming in the next release. ROIs in general have been a heavily requested feature and we are fully incorporating them into the SimBA pipeline, including analysis and visualization.

**Comment by 2909ft** [comment]
Thank you for the reply!

My idea was to use the ROI to help me define what I consider as "investigation" on my analysis; ie: whenever the mouse is within a certain distance of the ROI, I would label those frames as "investigation"

**Comment by sgoldenlab** [comment]
Thank for the explanation. Yes, that can be easily done with the new ROI function, but depending on how you want to incorporate ROIs into your analysis could also be done without ML, posthoc, on a ML classifier dataset. Lots of ways to accomplish that goal, looking forward to seeing how you decide to approach it.

I am going to leave this Issue open until we release the new ROI module so that others can comment as well if they like.

**Comment by 2909ft** [comment]
Thank you for the reply :) Is there any documentation somewhere that explains how to do that?

Best regards,
Filipa

**Comment by sgoldenlab** [comment]
There will be detailed documentation once we release it, not sure on exact time frame, but we will send an email to everyone on the listserve with the information when the release happens.

Here is a teaser! 
![ROI](https://user-images.githubusercontent.com/50497030/73094925-72c8cc00-3e96-11ea-9375-99df478d952a.gif)

**Comment by 2909ft** [comment]
Awesome! Thanks a lot!

**Comment by sgoldenlab** [comment]
Version 1.1 now includes full ROI support.  Please see documentation here: https://github.com/sgoldenlab/simba/blob/master/docs/ROI_tutorial.md
