### ISSUE TITLE
SLEAP File Import: Issues & Questions

### ISSUE THREAD

**Issue by MattKDawson** [sgoldenlab/simba#72]
Hi @sgoldenlab ! I actually have another issue when trying to import .SLP files into my project. When trying to import my .SLP file into my project, I receive the following error readout in the Anaconda prompt:

Traceback (most recent call last):
  File "c:\users\carol\anaconda3\envs\simba_env\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\SimBA.py", line 3048, in importh5
    importSLEAPbottomUP(self.configinifile,self.h5path.folder_path,idlist)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\simba\sleap_bottom_up_convert.py", line 138, in importSLEAPbottomUP
    dataDf.loc[len(dataDf)] = outRow
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 406, in _setitem_with_indexer
    return self._setitem_with_indexer_missing(indexer, value)
  File "c:\users\carol\anaconda3\envs\simba_env\lib\site-packages\pandas\core\indexing.py", line 647, in _setitem_with_indexer_missing
    raise ValueError("cannot set a row with mismatched columns")
ValueError: cannot set a row with mismatched columns

I also see the following message in the main SimBA window at the same time:

Warning: The video name could not be found in the .SLP meta-data table
SimBA therefore gives the imported CSV the same name as the SLP file.
To be sure that SimBAs slp import function works, make sure the .SLP file and the associated video file has the same file name - e.g., "Video1.slp" and "Video1.slp" before importing the videos and SLP files to SimBA.

Is this an issue with how my SLEAP model was created, or is this something to do with SimBA? My SLEAP model was mostly just a test and was created with different tracking points than what SimBA expects. I also trained trained my SLEAP model using the top-down training model and not the bottom-up model. Could these be creating this issue?

On a similar note, do you by chance know if there is an optimal resolution for capturing test footage? My experiments have been captured in 720x480 up until now but do you know if SimBA would benefit from a higher resolution?

Thanks! :)

**Comment by sgoldenlab** [comment]
Hi @MattKDawson - this warning happens when SimBA looks in the SLP h5 file, which should store the name of the video you are processing, but SimBA can't find this entry. The `ValueError` you are seeing may be related to this, because SimBA also can't find a the number of columns to match the number of body-parts you have. 

To me this suggests that something may have changed in SLEAP since I wrote this import code, and conversations with other sleap users I have had, suggests that SLEAP now may generate multiple SLP files. Do you see any other SLP file generated when you ran inference in SLEAP, and if you do, can you try to import this file into SimBA?   

For the optimal resolution: it's the smallest possible resolution where you can still reliably see the behaviors your are interested in.  This will make any pose-estimation and visual renderings in SimBA the fastest it can be without loosing reliable pose, which is most important for accurate classification.

**Comment by MattKDawson** [comment]
Hi @sgoldenlab ! After running an inference in SLEAP, I only see the SLEAP project file. SLEAP does have the option to export your inference as an .h5 file but that is not something automatically done by SLEAP.

Thank you for your input on the optimal resolution! 480p seems to work for SLEAP so far and my fingers are crossed that SimBA is also able to use that resolution for the behaviours I would like to capture.
